### ISSUE TITLE
more colored interface for tables

### ISSUE THREAD

**Issue by edib** [lesovsky/pgcenter#39]
activity screen should have a cpu usage column and screens can be colored with contrast colors.

**Comment by lesovsky** [comment]
activity screen is based on pg_stat_activity view and it doesn't provide info like cpu usage. i'd recommend to use top utility instead.
regarding to contrast color, explain pls what do you mean?

**Comment by edib** [comment]
I mean, all the data flowing on the screen are monochrome, a little bit hard to read, for example, I use pg_activity tool for cpu usage for the queries, it is limited compared to pgcenter but colored for diferent columns.

**Comment by lesovsky** [comment]
1) i've checked pg_activity, so that it shows per-process cpu usage and it looks useful, but I'd recommend to switch to "pg_stat_statements_timing" screen (using 'x' hotkey) and get more database-close info about which queries used a lot of cpu time (_t_cpu_t_ and _cpu_t_ columns). imho, it's more useful in a troubleshooting point of view. 
Anyway, I'm not refusing to implement this feature, but it requires some investigations in that direction.

2) about colors, it seems less possible to implement it with current ncurses colors possibilities. so at first glance, i'm not sure i will do that. sorry ))

**Comment by lesovsky** [comment]
just to clarify... what benefits does give you per-process cpu usage information?
from my practice of dba consultant, this information is a bit useless, because on hosts with high cpu utilization this information give just "nothing" to administrator.

![image](https://user-images.githubusercontent.com/953312/41201979-9d5293c2-6cdb-11e8-9da5-5a13b83246ef.png)

as you can see on the picture above, queries are executed with high cpu usage, and it's ok for this host - _cpu%_ just shows that processes are active and working. It's more useful to get information about which kind of queries use CPUs more than other queries and this is the next step of dba's investigations, so _t_cpu_t_ and _cpu_t_ columns are more appropriate and allows to answer on that question.

**Comment by edib** [comment]
Thank you, I haven't ever visited the "pg_stat_statements" screen. The information here seems very relevant. About coloring, yeah, this kind of things need time, this is just a suggestion.

**Comment by edib** [comment]
Thanks, I haven't ever checked that screen before. That is explanatory and satisfactory. Of course, coloring needs time, but would be good for this tool.
