### ISSUE TITLE
Support for pg_stat_statements in alternative schema

### ISSUE THREAD

**Issue by seafoodbuffet** [lesovsky/pgcenter#49]
I've got pg_stat_statements installed but not in the default schema for the user I've connected using. Is there a way for pgcenter to read it from a different schema?

**Comment by lesovsky** [comment]
Hi, sorry for late answer... was on PgConf.eu )))
You can use PGOPTIONS env variable, because used db driver have already supported all set of `libpq` [envvars](https://www.postgresql.org/docs/current/static/libpq-envars.html). Just run pgcenter in the following way (and don't forget replace EXAMPLE_SCHEMA to your schema):
```
PGOPTIONS="--search_path=EXAMPLE_SCHEMA" pgcenter top -U user dbname
```

**Comment by seafoodbuffet** [comment]
Thank you, that works perfectly. I did not even think about doing that.
