### ISSUE TITLE
PgStatStatementsIoQueryDefault has duplicated columns with different names

### ISSUE THREAD

**Issue by demonfoxkzn** [lesovsky/pgcenter#75]
probably I missed something but as I can see from source code PgStatStatementsIoQueryDefault 
columns with totals are identical with "current" values - ie 
t_hits = p.shared_blks_hit + p.local_blks_hit
hits = p.shared_blks_hit + p.local_blks_hit

SELECT
pg_get_userbyid(p.userid) AS user,
d.datname AS database,
p.shared_blks_hit + p.local_blks_hit AS t_hits,
(p.shared_blks_read + p.local_blks_read) * (SELECT current_setting('block_size')::int / 1024) AS t_reads,
(p.shared_blks_dirtied + p.local_blks_dirtied) * (SELECT current_setting('block_size')::int / 1024) AS t_dirtied,
(p.shared_blks_written + p.local_blks_written) * (SELECT current_setting('block_size')::int / 1024) AS t_written,
p.shared_blks_hit + p.local_blks_hit AS hits,
(p.shared_blks_read + p.local_blks_read) * (SELECT current_setting('block_size')::int / 1024) AS reads,
(p.shared_blks_dirtied + p.local_blks_dirtied) * (SELECT current_setting('block_size')::int / 1024) AS dirtied,
(p.shared_blks_written + p.local_blks_written) * (SELECT current_setting('block_size')::int / 1024) AS written,
p.calls AS calls,
left(md5(p.dbid::text || p.userid || p.queryid), 10) AS queryid
FROM pg_stat_statements p
JOIN pg_database d ON d.oid=p.dbid;

**Comment by lesovsky** [comment]
What is the question?

**Comment by demonfoxkzn** [comment]
what is the purpose of that duplicated columns?

**Comment by lesovsky** [comment]
As you can see in the stats shown by 'top', there can be two representation of the same stats.
For example any of pg_stat_statments, take a look at pg_stat_statements_general as a most simple example. There are two columns:
t_calls - total calls since stats reset
calls - number of calls per second
Both columns are based on the same column from pg_stat_statements (calls), but one of them is used for displaying totals, other for calculating delta.
Thus you can see "duplicates" in many stats queries.

**Comment by lesovsky** [comment]
@demonfoxkzn so, do you have any questions or this issue can be resolved?

**Comment by demonfoxkzn** [comment]
yes, I do apologize, you are right, the issue should be closed
